/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotel.componentes;

import com.hotel.controlador.DetalleDao;
import com.hotel.controlador.DetalleDaoImpl;
import com.hotel.controlador.HabitacionDao;
import com.hotel.controlador.HabitacionDaoImpl;
import com.hotel.controlador.ReservaDao;
import com.hotel.controlador.ReservaDaoImpl;
import com.hotel.modelo.Detalle;
import com.hotel.modelo.Habitacion;
import com.hotel.modelo.Usuario;
import com.hotel.utils.ReporteExcel;
import com.hotel.vista.ExtrasView;
import com.hotel.vista.ReservaEditar;
import com.hotel.vista.ReservaVista;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.BorderFactory;

import javax.swing.JButton;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 51901
 */
public class ReservaHabitacion extends javax.swing.JPanel {

    Usuario user3 = new Usuario();
    private List<JPanel> paneles;
    private List<JButton> botones;
    private List<JLabel> labels;
    HabitacionDao habitacionDao = new HabitacionDaoImpl();
    Habitacion habitacion = new Habitacion();
    ReservaDao reservaDao = new ReservaDaoImpl();
    DetalleDao detalleDao = new DetalleDaoImpl();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form ReservaHabitacion
     */
    public ReservaHabitacion() {
        initComponents();
        paneles = new ArrayList<>();
        botones = new ArrayList<>();
        labels = new ArrayList<>();

    }

    public ReservaHabitacion(Usuario user) {
        initComponents();
        paneles = new ArrayList<>();
        botones = new ArrayList<>();
        labels = new ArrayList<>();
        txtNombreUsuario.setText(String.valueOf(user.getId()));
        txtNombreUsuario.setVisible(false);
        user3 = user;
        verHabitaciones();
        
    }

    public void iniciarpaneles() {
        setLayout(new BorderLayout());
        Contenedor = new JPanel();
        Contenedor.setLayout(new GridLayout(3, 0, 10, 10)); // 0 filas, 3 columnas, 10 píxeles de espacio horizontal y vertical
        add(Contenedor, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        btnRegistrosReserva = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Contenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        btnEditarRegistroReserva = new javax.swing.JButton();
        btnExel = new javax.swing.JButton();

        btnActualizar.setText("Ver Habitaciones");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegistrosReserva.setText("Registros");
        btnRegistrosReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosReservaActionPerformed(evt);
            }
        });

        Contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Contenedor.setMinimumSize(new java.awt.Dimension(100, 100));
        Contenedor.setLayout(new java.awt.GridLayout(3, 0, 5, 5));
        jScrollPane1.setViewportView(Contenedor);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "N° Habitacion", "Cliente", "Fecha de reserva", "Fecha de Salida", "Precio Total"
            }
        ));
        jScrollPane2.setViewportView(tablaReservas);
        if (tablaReservas.getColumnModel().getColumnCount() > 0) {
            tablaReservas.getColumnModel().getColumn(0).setMinWidth(75);
            tablaReservas.getColumnModel().getColumn(0).setPreferredWidth(75);
            tablaReservas.getColumnModel().getColumn(0).setMaxWidth(75);
        }

        btnEditarRegistroReserva.setText("Editar");
        btnEditarRegistroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegistroReservaActionPerformed(evt);
            }
        });

        btnExel.setText("Reporte");
        btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditarRegistroReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEditarRegistroReserva)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrosReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnRegistrosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        verHabitaciones();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void verHabitaciones() {

        List<Habitacion> habitaciones = habitacionDao.listar();

        // Limpiar el contenedor antes de agregar nuevos labels
        Contenedor.removeAll();
        labels.clear();
        paneles.clear();
        // Agregar un JLabel por cada habitación
        for (Habitacion habitacion : habitaciones) {
            JPanel buttonPanel = new JPanel(new FlowLayout());
            JPanel panel = new JPanel(new BorderLayout());
            Font font = new Font("Arial", Font.BOLD, 17);
            Border border = BorderFactory.createLineBorder(Color.BLACK, 2);
            panel.setBorder(border);
            JLabel label = new JLabel(cambio2(habitacion));
            label.setFont(font);
            boolean estaOcuapado = true;

            JButton button = new JButton(cambioEstado(habitacion));
            button.addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    ReservaVista resVista = new ReservaVista(habitacion, user3);
                    resVista.setVisible(true);
                }
            });
            // Cambiar color del texto y fondo según el estado
            switch (habitacion.getEstado()) {
                case '1':
                    label.setForeground(Color.BLACK);
                    label.setBackground(Color.GREEN);
                    break;
                case '2':
                    estaOcuapado = false;
                    int id_detalle = detalleDao.buscarPoridHbaitacion(habitacion.getId());
                    Date fechaSalida = reservaDao.obtenerfechaSalida(id_detalle);
                    if (fechaSalida != null) {
                        Date fechaActual = new Date(); // Obtener la fecha actual

                        if (fechaSalida.after(fechaActual)) {
                            label.setForeground(Color.WHITE);
                            label.setBackground(Color.RED);
                            JButton button2 = new JButton("Extras");
                            buttonPanel.add(button2);
                            button2.addActionListener(new ActionListener() {

                                public void actionPerformed(ActionEvent e) {
                                    ExtrasView estExtrasView = new ExtrasView();
                                    estExtrasView.setVisible(true);
                                }
                            });

                        } else {
                            char estado = '1';
                            label.setForeground(Color.WHITE);
                            label.setBackground(Color.YELLOW);
                            JButton button3 = new JButton("Habilitar");
                            buttonPanel.add(button3);
                            button3.addActionListener(new ActionListener() {

                                public void actionPerformed(ActionEvent e) {
                                    habitacionDao.cambiarEstado(habitacion.getId(), estado);
                                }
                            });
                        }
                    }
                    break;
                default:
                    label.setForeground(Color.WHITE);
                    label.setBackground(Color.BLUE);
                    break;
            }

            label.setOpaque(true);

            buttonPanel.add(button);

            if (!estaOcuapado) {
                buttonPanel.remove(button);
            }

            panel.add(label, BorderLayout.CENTER);
            panel.add(buttonPanel, BorderLayout.PAGE_END);
            //panel.add(button, BorderLayout.PAGE_END);
            //panel.add(button2, BorderLayout.PAGE_END);

            Contenedor.add(panel);
            labels.add(label);
            botones.add(button);
            paneles.add(panel);

        }
        Contenedor.updateUI();
    }

    public String cambio(Habitacion habitacion) {
        return "Habitación: " + habitacion.getNumero()
                + " Tipo: " + habitacion.getId_tipo()
                + ", Precio: " + habitacion.getPrecio();

    }

    public String cambio2(Habitacion habitacion) {
        int tipo = habitacion.getId_tipo();
        String tipoHabitacion = "";
        switch (tipo) {
            case 1:
                tipoHabitacion = "Individual";
                break;
            case 2:
                tipoHabitacion = "Doble";
                break;
            case 3:
                tipoHabitacion = "Suite";
                break;

        }
        return "Nro: " + habitacion.getNumero() + "\n"
                + "\n Habitacion: " + tipoHabitacion;

    }

    public String cambioEstado(Habitacion habitacion) {
        if (habitacion.getEstado() == '1') {
            return "Reservar";
        } else {
            return "Desocupar";
        } //else {
        // return "Reservado";
        //}
    }

    //boton para la tabla
    private void btnRegistrosReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosReservaActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        llenarTabla();

    }//GEN-LAST:event_btnRegistrosReservaActionPerformed

    private void btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExelActionPerformed
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaReservas.getModel();
        ReporteExcel.generateReport(modeloTabla);

    }//GEN-LAST:event_btnExelActionPerformed

    private void btnEditarRegistroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegistroReservaActionPerformed
        int selectedRow = tablaReservas.getSelectedRow();

        if (selectedRow != -1) {
            Date fechaActual = new Date();
            Date fechaSalida = (Date) tablaReservas.getValueAt(selectedRow, 4);
            System.out.println(fechaActual + " " + fechaSalida);

            if (fechaSalida != null && fechaSalida.after(fechaActual)) {
                int idDetalle = (int) tablaReservas.getValueAt(selectedRow, 0);
                Detalle detalle = detalleDao.buscarPorId(idDetalle);
                ReservaEditar reservaEditar = new ReservaEditar(detalle, user3);
                reservaEditar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Este registro está terminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } 


    }//GEN-LAST:event_btnEditarRegistroReservaActionPerformed

    public void llenarTabla() {
        List<HashMap<String, Object>> lista = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tablaReservas.getModel();
        lista = detalleDao.listarDetalle();
        Object[] datos = new Object[6];
        model.setRowCount(0);
        for (HashMap<String, Object> detalle : lista) {

            datos[0] = detalle.get("id");
            datos[1] = detalle.get("N° habitacion");
            datos[2] = detalle.get("Cliente");
            datos[3] = detalle.get("fecha_reserva");
            datos[4] = detalle.get("fecha_salida");
            datos[5] = detalle.get("precio_total");

            model.addRow(datos);
        }

        tablaReservas.setModel(model);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditarRegistroReserva;
    private javax.swing.JButton btnExel;
    private javax.swing.JButton btnRegistrosReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaReservas;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
